name: Unzip File

on:
  push:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip ZIP
        run: unzip wa-group-clone.zip -d extracted

      - name: Commit hasil unzip
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto unzip wa-group-clone"
          git push
